### PR TITLE
Fix #19, fix README.md, fix hello.ml

### LINKED ISSUE #19: Error: Unbound module Topdirs
Error I get if I try to run an ocamlscript under a 5.1.0 ocaml switch.
It does not happen w/ earlier versions of ocaml.

### PR DESCRIPTION
**Pull request by jrfondren**
#19

### CODE REVIEW

**Comment by jrfondren** [comment]
this also works in OCaml 4.14.2. I'm unable to build older versions
